env:
  browser: true
  es6: true
  amd: true
  node: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  $: true
  window: true
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {}
